AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a VPC

Parameters: #1. TODO change order of parameters listed https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html
  VPCBlock:
    Type: String
    Default: 10.99.0.0/16

  DMZ1publicSubnet:
    Type: String
    Default: 10.99.1.0/24
    Description: "DMZ1public Subnet"

  DMZ2publicSubnet:
    Type: String
    Default: 10.99.2.0/24
    Description: "DMZ2public Subnet"

  AppLayer1privateSubnet:
    Type: String
    Default: 10.99.11.0/24
    Description: "AppLayer1private Subnet"

  AppLayer2privateSubnet:
    Type: String
    Default: 10.99.12.0/24
    Description: "AppLayer2private Subnet"

  DBLayer1privateSubnet:
    Type: String
    Default: 10.99.21.0/24
    Description: "DBLayer1private Subnet"

  DBLayer2privateSubnet:
    Type: String
    Default: 10.99.22.0/24
    Description: "DBLayer2private Subnet"

Resources:
  #============= VPC ==================
  CFVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CloudFormation

  #========IGW,PublicRT,RoutesForPublicRT,PrivateRT,RoutesForPrivateRT ==================
  #========DMZ1publicRTAssociation,DMZ2publicRTAssociation,AppLayer1privateRTAssociation,AppLayer2privateRTAssociation=====
  #===== EIPForNATGWs, NATGWs,

  #===== Internet Gateway ============
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: resource
          Value: CloudFormation
  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CFVPC
      InternetGatewayId: !Ref IGW

  #===== Public Route Tables =========
  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CFVPC
      Tags:
        - Key: resource
          Value: CloudFormation

  #======== Routes For PublicRT ==========
  RoutesForPublicRT:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW #!
    Properties:
      RouteTableId: !Ref PublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  #===== Private Route Tables =========
  PrivateRT1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CFVPC
      Tags:
        - Key: Name
          Value: PrivateRT1

  PrivateRT2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CFVPC
      Tags:
        - Key: Name
          Value: PrivateRT2

  #======= Second PrivateRT for MultiAZ ========
  ##################################
  ##################################
  ##################################

  #======== Routes For PrivateRT ==========
  RoutesForPrivateRTA:
    Type: AWS::EC2::Route
    DependsOn: NATGateway1 #!NATGatewayA
    Properties:
      RouteTableId: !Ref PrivateRT1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1

  RoutesForPrivateRTB:
    Type: AWS::EC2::Route
    DependsOn: NATGateway2 #!NATGatewayA
    Properties:
      RouteTableId: !Ref PrivateRT2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2

  #====== Associate Public Route for Public Subnets ====
  DMZ1publicRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZ1public
      RouteTableId: !Ref PublicRT

  DMZ2publicRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZ2public
      RouteTableId: !Ref PublicRT

  #====== Associate Private Route for Private Subnets ====
  AppLayer1privateRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppLayer1private
      RouteTableId: !Ref PrivateRT1

  AppLayer2privateRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppLayer2private
      RouteTableId: !Ref PrivateRT2

  #==== Route Table and Route Association for Internal only - Databases
  ############################################
  #TODO: DB association
  ############################################

  #======= ElasticIP for NAT Gateways ======
  NATGWEIP1:
    Type: AWS::EC2::EIP
    DependsOn: AttachIGW
    Properties:
      Domain: !Ref CFVPC

  NATGWEIP2:
    Type: AWS::EC2::EIP
    DependsOn: AttachIGW
    Properties:
      Domain: !Ref CFVPC

  #===== NATGWs =========
  NATGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachIGW
    Properties:
      SubnetId: !Ref DMZ1public
      AllocationId: !GetAtt NATGWEIP1.AllocationId
      Tags:
        - Key: Name
          Value: aws
        - Key: resource
          Value: CloudFormation

  NATGateway2:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachIGW
    Properties:
      SubnetId: !Ref DMZ2public
      AllocationId: !GetAtt NATGWEIP2.AllocationId
      Tags:
        - Key: Name
          Value: NATGateway2
        - Key: resource
          Value: CloudFormation
  #============= Subnets: DMZ1public,DMZ2public,AppLayer1private,AppLayer2private,DBLayer1private,DBLayer2private ==================
  DMZ1public:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref DMZ1publicSubnet
      MapPublicIpOnLaunch: true
      Tags:
        - Key: resource
          Value: CloudFormation #TODO:  NAME and !Join [ "", [ !Ref Environment, "-Public-A" ] ]

  DMZ2public:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref DMZ2publicSubnet
      MapPublicIpOnLaunch: true
      Tags:
        - Key: resource
          Value: CloudFormation #TODO:!

  AppLayer1private:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref AppLayer1privateSubnet
      Tags:
        - Key: Name
          Value: AppLayer1private

  AppLayer2private:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [2, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref AppLayer2privateSubnet
      Tags:
        - Key: Name
          Value: CF-AppLayer2private #! Use Join with separator "-"

  DBLayer1private:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref DBLayer1privateSubnet
      Tags:
        - Key: Name
          Value: DBLayer1private #!

  DBLayer2private:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, "Fn::GetAZs": { Ref: "AWS::Region" }]
      VpcId: !Ref CFVPC
      CidrBlock: !Ref DBLayer2privateSubnet
      Tags:
        - Key: Name
          Value: DBLayer2private #!

#########
